import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
    return (
        <div>
            <Head>
                <title>JS Portfolio</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main>
                <section
                    id='home'
                    className='h-screen container grid grid-cols-2 mx-auto content-center'
                >
                    <div className='flex flex-col gap-3'>
                        <h1 className='text-6xl'>
                            Hi, I am <b>Jonas</b>
                        </h1>
                        <p className='text-2xl font-light'>
                            Your next junior Front-end developer
                        </p>
                        <div className='flex gap-4'>
                            <a
                                className='px-4 py-2.5 bg-red-400 text-white'
                                href=''
                            >
                                Resume
                            </a>
                            <Link href='about'>
                                <a className='px-4 py-2.5 bg-neutral-500 text-white'>
                                    About Me
                                </a>
                            </Link>
                        </div>
                    </div>
                </section>
            </main>

            <footer></footer>
        </div>
    );
}
